CREATE DATABASE IF NOT EXISTS STREAM_DATABASE;
 
CREATE SCHEMA IF NOT EXISTS STREAM_DATABASE.SILVER;
 
CREATE SCHEMA IF NOT EXISTS STREAM_DATABASE.GOLD;
 
CREATE WAREHOUSE IF NOT EXISTS MYWAREHOUSE
WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;



USE DATABASE STREAM_DATABASE;
USE SCHEMA SILVER;

CREATE SCHEMA STREAM_DATABASE.GOLD;

SHOW TABLES;

SELECT COUNT(*) FROM CAB_RIDES_SILVER;

USE SCHEMA STREAM_DATABASE.GOLD;


---------------- DIM DATE TABLE--------------------------

CREATE OR REPLACE TABLE DIM_DATE AS
SELECT DISTINCT
    RIDE_DATE AS DATE_KEY,
    RIDE_DATE,
    YEAR(RIDE_DATE) AS YEAR,
    MONTH(RIDE_DATE) AS MONTH,
    DAY(RIDE_DATE) AS DAY,
    DAYNAME(RIDE_DATE) AS DAY_NAME,
    WEEKOFYEAR(RIDE_DATE) AS WEEK_OF_YEAR,
    QUARTER(RIDE_DATE) AS QUARTER
FROM STREAM_DATABASE.SILVER.CAB_RIDES_SILVER
WHERE RIDE_DATE IS NOT NULL;

SELECT * FROM DIM_DATE;

-------------------------DIM DRIVER -----------------------

CREATE OR REPLACE TABLE DIM_DRIVER AS
SELECT DISTINCT
    driver_id,
    driver_name,
    driver_rating,
    driver_license
FROM STREAM_DATABASE.SILVER.CAB_RIDES_SILVER
WHERE driver_id IS NOT NULL;


CREATE OR REPLACE TABLE DIM_VEHICLE AS
SELECT DISTINCT
    VEHICLE_ID,
    VEHICLE_TYPE_ID,
    VEHICLE_MAKE_ID,
    VEHICLE_MODEL,
    VEHICLE_COLOR
FROM STREAM_DATABASE.SILVER.CAB_RIDES_SILVER
WHERE VEHICLE_ID IS NOT NULL;

SELECT * FROM DIM_VEHICLE;

-------------------------------------

CREATE OR REPLACE TABLE DIM_LOCATION AS
 
SELECT DISTINCT
    PICKUP_LOCATION_ID AS LOCATION_ID,
    PICKUP_CITY_ID AS CITY_ID,
    PICKUP_ADDRESS AS ADDRESS,
    PICKUP_LATITUDE AS LATITUDE,
    PICKUP_LONGITUDE AS LONGITUDE
FROM STREAM_DATABASE.SILVER.CAB_RIDES_SILVER
WHERE PICKUP_LOCATION_ID IS NOT NULL
 
UNION
 
SELECT DISTINCT
    DROPOFF_LOCATION_ID AS LOCATION_ID,
    DROPOFF_CITY_ID AS CITY_ID,
    DROPOFF_ADDRESS AS ADDRESS,
    DROPOFF_LATITUDE AS LATITUDE,
    DROPOFF_LONGITUDE AS LONGITUDE
FROM STREAM_DATABASE.SILVER.CAB_RIDES_SILVER
WHERE DROPOFF_LOCATION_ID IS NOT NULL;


SELECT * FROM DIM_LOCATION;

-----------------------------------------


CREATE OR REPLACE TABLE DIM_RIDE AS
SELECT DISTINCT
    PAYMENT_METHOD_ID,
    RIDE_STATUS_ID,
    CANCELLATION_REASON_ID,
    
FROM STREAM_DATABASE.SILVER.CAB_RIDES_SILVER;

SELECT * FROM DIM_RIDE;

-----------------------------------

CREATE OR REPLACE TABLE FCT_RIDES AS
 
SELECT
    HASH(
        VEHICLE_ID,
        BOOKING_TIMESTAMP,
        PICKUP_TIMESTAMP,
        DROPOFF_TIMESTAMP
    ) AS FACT_RIDE_KEY,
 
    RIDE_DATE AS DATE_KEY,
 
    VEHICLE_ID,
 
    PICKUP_LOCATION_ID,
 
    DROPOFF_LOCATION_ID,
 
    PAYMENT_METHOD_ID,
 
    RIDE_STATUS_ID,
 
    CANCELLATION_REASON_ID,
 
    DISTANCE_MILES,
    DURATION_MINUTES,
    PICKUP_HOUR,
 
    BASE_FARE,
    DISTANCE_FARE,
    TIME_FARE,
    SURGE_MULTIPLIER,
    SUBTOTAL,
    TIP_AMOUNT,
    TOTAL_FARE,
    RATING,
 
    TIP_PERCENTAGE,
    FARE_PER_MILE,
 
    DRIVER_RATING,
 
    BOOKING_TIMESTAMP,
    PICKUP_TIMESTAMP,
    DROPOFF_TIMESTAMP,
 
    EVENTPROCESSEDUTCTIME,
    EVENTENQUEUEDUTCTIME,
    PARTITIONID
 
FROM STREAM_DATABASE.SILVER.CAB_RIDES_SILVER;

SELECT * FROM FCT_RIDES;

----------------------------------------------------



SELECT * FROM STREAM_DATABASE.SILVER.CAB_RIDES_SILVER;

DESC TABLE STREAM_DATABASE.SILVER.CAB_RIDES_SILVER;